name: Update Documentation

on: push

jobs:
  neth-docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --prune --unshallow
    - name: Cloning poa-chain-spec repo
      run: git clone https://github.com/poanetwork/poa-chain-spec.git
    - name: Updating Poacore chainspec
      run: |
        cd poa-chain-spec/
        git checkout core
        cd ..
        cat src/Nethermind/Chains/poacore.json | jq ".nodes = $(cat poa-chain-spec/spec.json | jq ".nodes")" > src/Nethermind/Chains/poacore.json 
    - name: Updating Sokol chainspec
      run: |
        cd poa-chain-spec/
        git checkout sokol
        cd ..
        cat src/Nethermind/Chains/sokol.json | jq ".nodes = $(cat poa-chain-spec/spec.json | jq ".nodes")" > src/Nethermind/Chains/sokol.json 
    - name: Updating xDai chainspec
      run: |
        cd poa-chain-spec/
        git checkout dai
        cd ..
        cat src/Nethermind/Chains/xdai.json | jq ".nodes = $(cat poa-chain-spec/spec.json | jq ".nodes")" > src/Nethermind/Chains/xdai.json
    - name: Create Pull Request     
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update bootnodes
        body: |
          Nethermind bootnodes have been updated.
          - Files included - poacore.json, sokol.json, xdai.json
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        title: 'Updating Bootnodes'
        labels: bootnodes
        author-name: github-actions[bot]
        author-email: 41898282+github-actions[bot]@users.noreply.github.com
        committer-name: GitHub
        committer-email: noreply@github.com
        branch: bootnodes-update
        branch-suffix: short-commit-hash
        base: master
    - name: Checking Outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"


